# Generated by Django 4.0.6 on 2022-08-26 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='master',
            name='IsActive',
            field=models.BooleanField(default=False),
        ),
    ]
