# Generated by Django 4.0.6 on 2022-09-07 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume_app', '0003_alter_skill_level_reference'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skill',
            old_name='level',
            new_name='Level',
        ),
        migrations.RenameField(
            model_name='skill',
            old_name='skill',
            new_name='Skill',
        ),
    ]
